### ISSUE TITLE
New version 3.8.1 can't link to the external lib mtj

### ISSUE THREAD

**Issue by LingboTang** [bnjmn/weka#6]
I'm using `weka.jar` as my external lib in my project, but when I instantiate a `LinearRegression` class, I got the error as:

```
Exception in thread "main" java.lang.NoClassDefFoundError: no/uib/cipr/matrix/Matrix
	at IscoreRegression.main(IscoreRegression.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.lang.ClassNotFoundException: no.uib.cipr.matrix.Matrix
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 6 more
```

I think you linked to the `mtj.jar` inappropriately. However, `weka-3-6-12.jar` does not have this problem. So currently I'll just add the version 3.6.12 in my project.

**Comment by bnjmn** [comment]
Sorry @LingboTang this repo is just _a mirror_ of the weka project. No actual development goes on here. I'm not even sure how to put you in touch with development team there for any fixes. I've updated the repo today. Maybe they have addressed your issue.

You should check out their site if you would like to help them: http://www.cs.waikato.ac.nz/ml/weka/index.html

**Comment by LingboTang** [comment]
I see what you mean, I'll try to contact with them.

**Comment by karmazinkd** [comment]
I had the same problem, I downloaded the latest stable weka 3.8, extracted it and got a weka.jar. But I faced this exception when trying to create a LinearRegression instance.

To fix this: I just extracted these 3 libs from weka.jar and explicitly added in my project: arpack_combined.jar
core.jar
mtj.jar
